<?php

/** @var $viewModel Highlight\HighlightProduct\ViewModel\HighlightProduct */

$viewModel = $block->getViewModel();
$product = $viewModel->getProduct();
?>

<?php if($product): ?>

<section class="highlight">
    <div class="highlight__card">
        <a class="highlight__card__title" href="<?= $block->escapeUrl($product->getProductUrl()); ?>"><?= $block->escapeHtml($product->getName()); ?></a>
        <figure class="highlight__card__image">
            <a class="highlight__card__title" href="<?= $block->escapeUrl($product->getProductUrl()); ?>">
                <img src="<?= $escaper->escapeUrl($viewModel->getImage($product)) ?>"
                alt="<?= $block->escapeHtml($product->getName()); ?>">
            </a>
        </figure>
        <p class="highlight__card__price"><?= $product->getFormatedPrice(); ?></p>
        <input class="highlight__card__qty" type="number" value="<?= $viewModel->getStockQty($product); ?>" disabled>
    </div>
</section>

<?php endif; ?>
